spring:
  profiles:
    include: local

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:hodolog;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
  logging:
    level:
      org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: DEBUG
  data:
    web:
      pageable:
        max-page-size: 2000
        default-page-size: 20
        one-indexed-parameters: true
    redis:
      host: 127.0.0.1
      port: 6379
  sql:
    init:
      mode: embedded

  jwt:
    secret: "yourasuperbsecurecrandomdsecretekeyfthatgishlongienoughjtokbelsafe13212345678901234567890"
    accessExpirationMs: 3600000 # 1 hour
    refreshExpirationMs: 86400000 # 1 day

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your_google_client_id_here
            client-secret: your_google_client_secret_here
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope:
              - profile
              - email

logging:
  level:
    root: info
    com.ulsan.climbing: debug
